[package]
name = "android_proxy_setter"
version = "0.1.2"
edition = "2021"

[dependencies]
local-ip-address = "0.5.6"
colored = "2.0"
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
